import Foundation

// Follow macOS language preferences. The environment override is for tests and demo renders.
enum Localization {
    static var language: String {
        let preferred = ProcessInfo.processInfo.environment["NODEPEEK_LANGUAGE"] ?? Locale.preferredLanguages.first ?? "en"
        return preferred.lowercased().hasPrefix("zh") ? "zh-Hans" : "en"
    }
    static let english: [String: String] = [
        "25 秒未收到指标，请检查网络、SSH 或远程 python3。": "No metrics received for 25 seconds. Check the network, SSH connection, and remote Python 3.",
        "CPU / 内存为系统视角，可能包含同机其他任务。": "CPU and memory reflect the remote system, including other workloads.",
        "CPU · {0} 逻辑核": "CPU · {0} threads",
        "CPU、内存与 GPU 实时用量 · 每 5 秒更新": "Live CPU, memory and GPU metrics · every 5 seconds",
        "GPU 列显示该机最高利用率；显存为可见 GPU 合计。离线时不展示旧数值。": "GPU shows peak utilization across visible devices; VRAM is their combined memory. Offline values are hidden.",
        "GPU 指标不可用": "GPU metrics unavailable",
        "GPU 最高": "Peak GPU",
        "RM · 离线": "RM · Offline",
        "NodePeek 远程资源监控": "NodePeek remote resource monitor",
        "SSH 启动失败": "SSH failed to start",
        "SSH 或采集程序退出（{0}）": "SSH or collector exited ({0})",
        "SSH 端口拒绝连接": "SSH connection refused",
        "SSH 认证失败": "SSH authentication failed",
        "SSH、Python 3 与系统指标采集正常": "SSH, Python 3 and system metrics are working",
        "Slurm 节点访问受限": "Slurm node access restricted",
        "{0} / {1} 台在线": "{0} / {1} hosts online",
        "{0} 张可见 GPU": "{0} visible GPUs",
        "✓ 登录时启动": "✓ Launch at login",
        "不支持的远端系统": "Unsupported remote system",
        "主机名无法解析": "Hostname could not be resolved",
        "主机指纹发生变化": "Host key has changed",
        "主机身份尚未确认": "Host identity not verified",
        "从左下角「管理监控机器」选择 SSH 别名。": "Select SSH aliases from Manage hosts in the lower-left corner.",
        "从本机 SSH 配置中选择 Linux 机器。仅连接选中的机器，复用现有密钥与跳板设置。": "Choose Linux hosts from your SSH config. Only selected hosts are contacted, using your existing keys and jump hosts.",
        "以下为上次采集数据": "Showing the last received sample",
        "休眠中": "Sleeping",
        "使用本机 SSH 配置连接": "Uses your local SSH config",
        "保存后点击「重新读取」。通配符 Host 不会作为机器列出。": "Save the config and click Reload. Wildcard Host patterns are not listed as machines.",
        "先在终端确认 SSH 可以连接，再检查远端 python3 和 nvidia-smi。下方保留本次错误输出供排查。": "Verify SSH in Terminal, then check remote python3 and nvidia-smi. The error output below may help diagnose the problem.",
        "全部机器": "All hosts",
        "全部机器总览": "All hosts overview",
        "内存 GiB": "RAM GiB",
        "利用率": "Utilization",
        "功耗": "Power",
        "取消": "Cancel",
        "向管理员核实新指纹。确认是重装或更换机器后，再更新对应的 known_hosts 记录。应用不会自动忽略身份校验。": "Verify the new fingerprint with the administrator. Update the corresponding known_hosts entry only after confirming the change. The app never bypasses host verification.",
        "在 Finder 中显示 SSH 配置": "Reveal SSH config in Finder",
        "在终端运行下面的 SSH 命令，核对主机指纹后完成首次连接。": "Run the SSH command below in Terminal and verify the host fingerprint to complete the first connection.",
        "在远端运行 nvidia-smi 检查驱动。没有 NVIDIA GPU 的机器仍可监控 CPU 和内存。": "Run nvidia-smi on the remote host to check its driver. CPU and memory monitoring still work without an NVIDIA GPU.",
        "复制": "Copy",
        "完成": "Done",
        "已复制": "Copied",
        "已暂停": "Paused",
        "已检测到 {0} 张 NVIDIA GPU。": "Detected {0} NVIDIA GPUs.",
        "已连接": "Connected",
        "已选 {0} 台": "{0} selected",
        "开始监控": "Start monitoring",
        "当前 CPU 和内存采集需要 Linux 的 /proc 文件系统，请选择 Linux 机器。": "CPU and memory collection currently requires Linux and its /proc filesystem.",
        "当前监控已暂停，请先在主窗口继续监控。": "Monitoring is paused. Resume it in the main window first.",
        "打开主窗口": "Open main window",
        "拖拽排序": "Drag to reorder",
        "搜索 SSH 别名": "Search SSH aliases",
        "操作": "Action",
        "显存 GiB": "VRAM GiB",
        "显示菜单栏图标": "Show menu bar icon",
        "暂停": "Pause",
        "暂停全部监控": "Pause all monitoring",
        "最近 CPU 利用率": "Recent CPU utilization",
        "最近最高 GPU 利用率": "Recent peak GPU utilization",
        "未找到可用 SSH 别名": "No SSH aliases found",
        "未选择机器": "No host selected",
        "本次错误输出（可能包含主机名或路径）": "Error output (may contain hostnames or paths)",
        "机器": "Host",
        "机器 / 状态": "Host / status",
        "检查 SSH 别名和 HostName 拼写；若是内网域名，请先连接相应 VPN 或网络。": "Check the SSH alias and HostName spelling. Connect to the appropriate VPN or network for internal domains.",
        "检查 SSH 配置中的 User 和 IdentityFile。若密钥有口令，请在终端用 ssh-add 解锁密钥，再重新连接。应用使用非交互认证。": "Check User and IdentityFile in your SSH config. Unlock passphrase-protected keys with ssh-add in Terminal, then retry. The app uses non-interactive authentication.",
        "检查机器是否开机、SSH 服务是否运行，以及配置中的端口是否正确。": "Check that the host is on, SSH is running, and the configured port is correct.",
        "欢迎使用 NodePeek": "Welcome to NodePeek",
        "正在等待连接结果。首次连接和跳板机认证可能需要几秒钟。": "Waiting for a connection result. Initial connections and jump hosts may take a few seconds.",
        "此节点要求你有正在运行的作业。先申请节点资源，或选择集群允许访问的登录节点。": "This node requires an active job allocation. Request resources first, or choose a login node permitted by your cluster.",
        "每 5 秒更新": "Updates every 5s",
        "没有匹配的别名": "No matching aliases",
        "添加一台远程机器": "Add a remote host",
        "温度": "Temp",
        "点击 +，从 SSH 配置中添加机器。": "Click + to add hosts from your SSH config.",
        "点击 × 隐藏窗口，后台监控继续；点击 Dock 图标恢复。": "Close hides the window. Monitoring continues; click the Dock icon to restore.",
        "登录时启动": "Launch at login",
        "确认机器在线，检查 VPN、跳板机、防火墙和 SSH 端口。应用会自动重试，也可以手动重新连接。": "Confirm the host is online. Check the VPN, jump host, firewall and SSH port. The app retries automatically; you can also reconnect manually.",
        "离线 · {0} 秒后重试": "Offline · retry in {0}s",
        "等待远程指标…": "Waiting for remote metrics…",
        "等待连接": "Waiting",
        "管理监控机器": "Manage hosts",
        "系统内存": "System memory",
        "终端检查命令": "Terminal check command",
        "继续": "Resume",
        "继续监控": "Resume monitoring",
        "网络连接超时或不可达": "Network timeout or unreachable",
        "菜单栏显示用量文字": "Show metrics in menu bar",
        "请先在 ~/.ssh/config 添加明确的 Host 别名，例如：": "Add an explicit Host alias to ~/.ssh/config, for example:",
        "请在系统设置 → 通用 → 登录项中允许 NodePeek。": "Allow NodePeek in System Settings → General → Login Items.",
        "请在远端安装 python3，并确保非交互 SSH 会话的 PATH 能找到它。不需要安装额外 Python 包。": "Install python3 on the remote host and ensure it is on the non-interactive SSH PATH. No extra Python packages are needed.",
        "远程机器": "Remote hosts",
        "远程机器，可拖拽排序": "Remote hosts, drag to reorder",
        "远端缺少 Python 3": "Remote Python 3 is missing",
        "远端需要 Python 3；NVIDIA GPU 指标需要 nvidia-smi。首次使用请先在终端确认 SSH 能连接。": "Remote hosts need Python 3; NVIDIA metrics need nvidia-smi. Verify SSH in Terminal before the first connection.",
        "连接中…": "Connecting…",
        "连接诊断": "Diagnostics",
        "连接超时 · 即将重试": "Connection timed out · retrying",
        "退出 NodePeek": "Quit NodePeek",
        "选择 SSH 机器，开始监控": "Choose SSH hosts to start monitoring",
        "选择机器": "Choose hosts",
        "选择机器…": "Choose hosts…",
        "选择监控机器": "Choose monitored hosts",
        "选择要监控的 SSH 机器": "Choose SSH hosts to monitor",
        "采集响应超时": "Collector response timed out",
        "采集脚本缺失": "Collector script missing",
        "重新检查": "Check again",
        "重新读取": "Reload",
        "重新读取 SSH 配置": "Reload SSH config",
        "重新连接": "Reconnect",
        "重新连接当前机器": "Reconnect current host",
        "隐藏窗口，继续后台监控": "Hide window and keep monitoring",
    ]
}
func L(_ key: String, _ arguments: CustomStringConvertible...) -> String {
    var result = Localization.language == "zh-Hans" ? key : (Localization.english[key] ?? key)
    for (index, argument) in arguments.enumerated() {
        result = result.replacingOccurrences(of: "{\(index)}", with: argument.description)
    }
    return result
}
